//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : MetaMask Unity SDK ABI Code Generator
//   Input filename:  Contracts.sol
//   Output filename: Contracts.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------

using System;
using System.Numerics;
using System.Threading.Tasks;
using evm.net;
using evm.net.Models;

namespace Contracts
{
	#if UNITY_EDITOR || !ENABLE_MONO
	[BackedType(typeof(TOD721Backing))]
	#endif
	public interface TOD721 : IContract
	{
		[EvmConstructorMethod]
		Task<TOD721> DeployNew();
		
		[EvmMethodInfo(Name = "approve", View = false)]
		Task<Transaction> Approve(EvmAddress to, BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "balanceOf", View = true)]
		Task<BigInteger> BalanceOf(EvmAddress owner, CallOptions options = default);
		
		[EvmMethodInfo(Name = "baseURI", View = true)]
		Task<String> BaseURI();
		
		[EvmMethodInfo(Name = "cost", View = true)]
		Task<BigInteger> Cost();
		
		[EvmMethodInfo(Name = "getApproved", View = true)]
		Task<EvmAddress> GetApproved(BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "gift", View = false)]
		Task<Transaction> Gift(BigInteger[] quantity, EvmAddress[] recipient, CallOptions options = default);
		
		[EvmMethodInfo(Name = "isApprovedForAll", View = true)]
		Task<Boolean> IsApprovedForAll(EvmAddress owner, [EvmParameterInfo(Type = "address", Name = "operator")] EvmAddress @operator, CallOptions options = default);
		
		[EvmMethodInfo(Name = "maxMint", View = true)]
		Task<BigInteger> MaxMint();
		
		[EvmMethodInfo(Name = "maxSupply", View = true)]
		Task<BigInteger> MaxSupply();
		
		[EvmMethodInfo(Name = "mint", View = false)]
		Task<Transaction> Mint(BigInteger _mintAmount, CallOptions options = default);
		
		[EvmMethodInfo(Name = "mintPresale", View = false)]
		Task<Transaction> MintPresale(BigInteger _mintAmount, CallOptions options = default);
		
		[EvmMethodInfo(Name = "name", View = true)]
		Task<String> Name();
		
		[EvmMethodInfo(Name = "owner", View = true)]
		Task<EvmAddress> Owner();
		
		[EvmMethodInfo(Name = "ownerOf", View = true)]
		Task<EvmAddress> OwnerOf(BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "paused", View = true)]
		Task<Boolean> Paused();
		
		[EvmMethodInfo(Name = "payee", View = true)]
		Task<EvmAddress> Payee(BigInteger index, CallOptions options = default);
		
		[EvmMethodInfo(Name = "presaleActive", View = true)]
		Task<Boolean> PresaleActive();
		
		[EvmMethodInfo(Name = "presaleSet", View = false)]
		Task<Transaction> PresaleSet(EvmAddress[] _addresses, BigInteger[] _amounts, CallOptions options = default);
		
		[EvmMethodInfo(Name = "presaleWhitelist", View = true)]
		Task<BigInteger> PresaleWhitelist([EvmParameterInfo(Type = "address", Name = "")] EvmAddress addr, CallOptions options = default);
		
		[EvmMethodInfo(Name = "publicSaleActive", View = true)]
		Task<Boolean> PublicSaleActive();
		
		[EvmMethodInfo(Name = "release", View = false)]
		Task<Transaction> Release(EvmAddress account, CallOptions options = default);
		
		[EvmMethodInfo(Name = "release", View = false)]
		Task<Transaction> Release(EvmAddress token, EvmAddress account, CallOptions options = default);
		
		[EvmMethodInfo(Name = "released", View = true)]
		Task<BigInteger> Released(EvmAddress token, EvmAddress account, CallOptions options = default);
		
		[EvmMethodInfo(Name = "released", View = true)]
		Task<BigInteger> Released(EvmAddress account, CallOptions options = default);
		
		[EvmMethodInfo(Name = "renounceOwnership", View = false)]
		Task<Transaction> RenounceOwnership();
		
		[EvmMethodInfo(Name = "safeTransferFrom", View = false)]
		Task<Transaction> SafeTransferFrom(EvmAddress from, EvmAddress to, BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "safeTransferFrom", View = false)]
		Task<Transaction> SafeTransferFrom(EvmAddress from, EvmAddress to, BigInteger tokenId, Byte[] _data, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setApprovalForAll", View = false)]
		Task<Transaction> SetApprovalForAll([EvmParameterInfo(Type = "address", Name = "operator")] EvmAddress @operator, Boolean approved, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setBaseURI", View = false)]
		Task<Transaction> SetBaseURI(String _newBaseURI, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setCost", View = false)]
		Task<Transaction> SetCost(BigInteger _newCost, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setMaxMint", View = false)]
		Task<Transaction> SetMaxMint(BigInteger _newmaxMint, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setMaxSupply", View = false)]
		Task<Transaction> SetMaxSupply(BigInteger _newMaxSupply, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setPresaleSaleStatus", View = false)]
		Task<Transaction> SetPresaleSaleStatus(Boolean _status, CallOptions options = default);
		
		[EvmMethodInfo(Name = "setPublicSaleStatus", View = false)]
		Task<Transaction> SetPublicSaleStatus(Boolean _status, CallOptions options = default);
		
		[EvmMethodInfo(Name = "shares", View = true)]
		Task<BigInteger> Shares(EvmAddress account, CallOptions options = default);
		
		[EvmMethodInfo(Name = "supportsInterface", View = true)]
		Task<Boolean> SupportsInterface([EvmParameterInfo(Type = "bytes4", Name = "interfaceId")] Byte[] interfaceId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "symbol", View = true)]
		Task<String> Symbol();
		
		[EvmMethodInfo(Name = "tokenByIndex", View = true)]
		Task<BigInteger> TokenByIndex(BigInteger index, CallOptions options = default);
		
		[EvmMethodInfo(Name = "tokenOfOwnerByIndex", View = true)]
		Task<BigInteger> TokenOfOwnerByIndex(EvmAddress owner, BigInteger index, CallOptions options = default);
		
		[EvmMethodInfo(Name = "tokenURI", View = true)]
		Task<String> TokenURI(BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "tokensOfOwner", View = true)]
		Task<BigInteger[]> TokensOfOwner(EvmAddress owner, CallOptions options = default);
		
		[EvmMethodInfo(Name = "totalReleased", View = true)]
		Task<BigInteger> TotalReleased(EvmAddress token, CallOptions options = default);
		
		[EvmMethodInfo(Name = "totalReleased", View = true)]
		Task<BigInteger> TotalReleased();
		
		[EvmMethodInfo(Name = "totalShares", View = true)]
		Task<BigInteger> TotalShares();
		
		[EvmMethodInfo(Name = "totalSupply", View = true)]
		Task<BigInteger> TotalSupply();
		
		[EvmMethodInfo(Name = "transferFrom", View = false)]
		Task<Transaction> TransferFrom(EvmAddress from, EvmAddress to, BigInteger tokenId, CallOptions options = default);
		
		[EvmMethodInfo(Name = "transferOwnership", View = false)]
		Task<Transaction> TransferOwnership(EvmAddress newOwner, CallOptions options = default);
		
		[EvmMethodInfo(Name = "withdraw", View = false)]
		Task<Transaction> Withdraw();
		
		[EvmMethodInfo(Name = "withdrawSplit", View = false)]
		Task<Transaction> WithdrawSplit();
		
	}
}
